/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbonnementRouteImport } from './routes/abonnement'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as NouveautesRouteImport } from './routes/nouveautes'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnnoncesRouteImport } from './routes/admin.annonces'
import { Route as AdminFacturationRouteImport } from './routes/admin.facturation'
import { Route as AdminFinancesRouteImport } from './routes/admin.finances'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPaiementsRouteImport } from './routes/admin.paiements'
import { Route as AdminPrixRouteImport } from './routes/admin.prix'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AtelierIndexRouteImport } from './routes/atelier.index'
import { Route as AtelierIdRouteImport } from './routes/atelier.$id'
import { Route as AtelierNouveauRouteImport } from './routes/atelier.nouveau'
import { Route as AtelierPlanRouteImport } from './routes/atelier.plan'
import { Route as BoutiquesIndexRouteImport } from './routes/boutiques.index'
import { Route as BoutiquesIdRouteImport } from './routes/boutiques.$id'
import { Route as BoutiquesNouveauRouteImport } from './routes/boutiques.nouveau'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as ClientsNouveauRouteImport } from './routes/clients.nouveau'
import { Route as ComputerCarnetRouteImport } from './routes/computer/carnet'
import { Route as ComputerHistoriqueRouteImport } from './routes/computer/historique'
import { Route as ConsumableHistoriqueRouteImport } from './routes/consumable/historique'
import { Route as OutilsIndexRouteImport } from './routes/outils.index'
import { Route as OutilsIdRouteImport } from './routes/outils.$id'
import { Route as ParametresEmplacementsRouteImport } from './routes/parametres.emplacements'
import { Route as PhoneCarnetRouteImport } from './routes/phone/carnet'
import { Route as PhoneHistoriqueRouteImport } from './routes/phone/historique'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as SalesCommandesRouteImport } from './routes/sales/commandes'
import { Route as SalesLivraisonsRouteImport } from './routes/sales/livraisons'
import { Route as SalesNouveauRouteImport } from './routes/sales/nouveau'
import { Route as SallesCommandesRouteImport } from './routes/salles/commandes'
import { Route as AdminModulesIndexRouteImport } from './routes/admin.modules.index'
import { Route as AdminModulesAjouterRouteImport } from './routes/admin.modules.ajouter'
import { Route as AdminModulesNouveauRouteImport } from './routes/admin.modules.nouveau'
import { Route as AdminSupportFaqRouteImport } from './routes/admin.support.faq'
import { Route as AdminSupportMessagesRouteImport } from './routes/admin.support.messages'
import { Route as AdminTenantsIdRouteImport } from './routes/admin.tenants.$id'
import { Route as AdminTenantsHistoriqueRouteImport } from './routes/admin.tenants.historique'
import { Route as ComputerAtelierIndexRouteImport } from './routes/computer/atelier/index'
import { Route as ComputerAtelierIdRouteImport } from './routes/computer/atelier/$id'
import { Route as ComputerAtelierNouveauRouteImport } from './routes/computer/atelier/nouveau'
import { Route as ConsumableStockIndexRouteImport } from './routes/consumable/stock/index'
import { Route as ConsumableStockIdRouteImport } from './routes/consumable/stock/$id'
import { Route as ConsumableStockNouveauRouteImport } from './routes/consumable/stock/nouveau'
import { Route as PhoneAtelierIndexRouteImport } from './routes/phone/atelier/index'
import { Route as PhoneAtelierIdRouteImport } from './routes/phone/atelier/$id'
import { Route as PhoneAtelierNouveauRouteImport } from './routes/phone/atelier/nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementRoute = AbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveautesRoute = NouveautesRouteImport.update({
  id: '/nouveautes',
  path: '/nouveautes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnoncesRoute = AdminAnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturationRoute = AdminFacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancesRoute = AdminFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrixRoute = AdminPrixRouteImport.update({
  id: '/prix',
  path: '/prix',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AtelierIndexRoute = AtelierIndexRouteImport.update({
  id: '/atelier/',
  path: '/atelier/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierIdRoute = AtelierIdRouteImport.update({
  id: '/atelier/$id',
  path: '/atelier/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierNouveauRoute = AtelierNouveauRouteImport.update({
  id: '/atelier/nouveau',
  path: '/atelier/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierPlanRoute = AtelierPlanRouteImport.update({
  id: '/atelier/plan',
  path: '/atelier/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesIndexRoute = BoutiquesIndexRouteImport.update({
  id: '/boutiques/',
  path: '/boutiques/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesIdRoute = BoutiquesIdRouteImport.update({
  id: '/boutiques/$id',
  path: '/boutiques/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesNouveauRoute = BoutiquesNouveauRouteImport.update({
  id: '/boutiques/nouveau',
  path: '/boutiques/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNouveauRoute = ClientsNouveauRouteImport.update({
  id: '/clients/nouveau',
  path: '/clients/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerCarnetRoute = ComputerCarnetRouteImport.update({
  id: '/computer/carnet',
  path: '/computer/carnet',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerHistoriqueRoute = ComputerHistoriqueRouteImport.update({
  id: '/computer/historique',
  path: '/computer/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumableHistoriqueRoute = ConsumableHistoriqueRouteImport.update({
  id: '/consumable/historique',
  path: '/consumable/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsIndexRoute = OutilsIndexRouteImport.update({
  id: '/outils/',
  path: '/outils/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsIdRoute = OutilsIdRouteImport.update({
  id: '/outils/$id',
  path: '/outils/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresEmplacementsRoute = ParametresEmplacementsRouteImport.update({
  id: '/emplacements',
  path: '/emplacements',
  getParentRoute: () => ParametresRoute,
} as any)
const PhoneCarnetRoute = PhoneCarnetRouteImport.update({
  id: '/phone/carnet',
  path: '/phone/carnet',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneHistoriqueRoute = PhoneHistoriqueRouteImport.update({
  id: '/phone/historique',
  path: '/phone/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCommandesRoute = SalesCommandesRouteImport.update({
  id: '/sales/commandes',
  path: '/sales/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLivraisonsRoute = SalesLivraisonsRouteImport.update({
  id: '/sales/livraisons',
  path: '/sales/livraisons',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNouveauRoute = SalesNouveauRouteImport.update({
  id: '/sales/nouveau',
  path: '/sales/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const SallesCommandesRoute = SallesCommandesRouteImport.update({
  id: '/salles/commandes',
  path: '/salles/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModulesIndexRoute = AdminModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminModulesRoute,
} as any)
const AdminModulesAjouterRoute = AdminModulesAjouterRouteImport.update({
  id: '/ajouter',
  path: '/ajouter',
  getParentRoute: () => AdminModulesRoute,
} as any)
const AdminModulesNouveauRoute = AdminModulesNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => AdminModulesRoute,
} as any)
const AdminSupportFaqRoute = AdminSupportFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminSupportRoute,
} as any)
const AdminSupportMessagesRoute = AdminSupportMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminSupportRoute,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTenantsRoute,
} as any)
const AdminTenantsHistoriqueRoute = AdminTenantsHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AdminTenantsRoute,
} as any)
const ComputerAtelierIndexRoute = ComputerAtelierIndexRouteImport.update({
  id: '/computer/atelier/',
  path: '/computer/atelier/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerAtelierIdRoute = ComputerAtelierIdRouteImport.update({
  id: '/computer/atelier/$id',
  path: '/computer/atelier/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerAtelierNouveauRoute = ComputerAtelierNouveauRouteImport.update({
  id: '/computer/atelier/nouveau',
  path: '/computer/atelier/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumableStockIndexRoute = ConsumableStockIndexRouteImport.update({
  id: '/consumable/stock/',
  path: '/consumable/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumableStockIdRoute = ConsumableStockIdRouteImport.update({
  id: '/consumable/stock/$id',
  path: '/consumable/stock/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumableStockNouveauRoute = ConsumableStockNouveauRouteImport.update({
  id: '/consumable/stock/nouveau',
  path: '/consumable/stock/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneAtelierIndexRoute = PhoneAtelierIndexRouteImport.update({
  id: '/phone/atelier/',
  path: '/phone/atelier/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneAtelierIdRoute = PhoneAtelierIdRouteImport.update({
  id: '/phone/atelier/$id',
  path: '/phone/atelier/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneAtelierNouveauRoute = PhoneAtelierNouveauRouteImport.update({
  id: '/phone/atelier/nouveau',
  path: '/phone/atelier/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/admin': typeof AdminRouteWithChildren
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/equipe': typeof EquipeRoute
  '/historique': typeof HistoriqueRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveautes': typeof NouveautesRoute
  '/parametres': typeof ParametresRouteWithChildren
  '/profil': typeof ProfilRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/statistiques': typeof StatistiquesRoute
  '/admin/annonces': typeof AdminAnnoncesRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/modules': typeof AdminModulesRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/prix': typeof AdminPrixRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/atelier/$id': typeof AtelierIdRoute
  '/atelier/nouveau': typeof AtelierNouveauRoute
  '/atelier/plan': typeof AtelierPlanRoute
  '/boutiques/$id': typeof BoutiquesIdRoute
  '/boutiques/nouveau': typeof BoutiquesNouveauRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/nouveau': typeof ClientsNouveauRoute
  '/computer/carnet': typeof ComputerCarnetRoute
  '/computer/historique': typeof ComputerHistoriqueRoute
  '/consumable/historique': typeof ConsumableHistoriqueRoute
  '/outils/$id': typeof OutilsIdRoute
  '/parametres/emplacements': typeof ParametresEmplacementsRoute
  '/phone/carnet': typeof PhoneCarnetRoute
  '/phone/historique': typeof PhoneHistoriqueRoute
  '/sales/commandes': typeof SalesCommandesRoute
  '/sales/livraisons': typeof SalesLivraisonsRoute
  '/sales/nouveau': typeof SalesNouveauRoute
  '/salles/commandes': typeof SallesCommandesRoute
  '/admin/': typeof AdminIndexRoute
  '/atelier/': typeof AtelierIndexRoute
  '/boutiques/': typeof BoutiquesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/outils/': typeof OutilsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/admin/modules/ajouter': typeof AdminModulesAjouterRoute
  '/admin/modules/nouveau': typeof AdminModulesNouveauRoute
  '/admin/support/faq': typeof AdminSupportFaqRoute
  '/admin/support/messages': typeof AdminSupportMessagesRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/historique': typeof AdminTenantsHistoriqueRoute
  '/computer/atelier/$id': typeof ComputerAtelierIdRoute
  '/computer/atelier/nouveau': typeof ComputerAtelierNouveauRoute
  '/consumable/stock/$id': typeof ConsumableStockIdRoute
  '/consumable/stock/nouveau': typeof ConsumableStockNouveauRoute
  '/phone/atelier/$id': typeof PhoneAtelierIdRoute
  '/phone/atelier/nouveau': typeof PhoneAtelierNouveauRoute
  '/admin/modules/': typeof AdminModulesIndexRoute
  '/computer/atelier/': typeof ComputerAtelierIndexRoute
  '/consumable/stock/': typeof ConsumableStockIndexRoute
  '/phone/atelier/': typeof PhoneAtelierIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/equipe': typeof EquipeRoute
  '/historique': typeof HistoriqueRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveautes': typeof NouveautesRoute
  '/parametres': typeof ParametresRouteWithChildren
  '/profil': typeof ProfilRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/statistiques': typeof StatistiquesRoute
  '/admin/annonces': typeof AdminAnnoncesRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/prix': typeof AdminPrixRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/atelier/$id': typeof AtelierIdRoute
  '/atelier/nouveau': typeof AtelierNouveauRoute
  '/atelier/plan': typeof AtelierPlanRoute
  '/boutiques/$id': typeof BoutiquesIdRoute
  '/boutiques/nouveau': typeof BoutiquesNouveauRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/nouveau': typeof ClientsNouveauRoute
  '/computer/carnet': typeof ComputerCarnetRoute
  '/computer/historique': typeof ComputerHistoriqueRoute
  '/consumable/historique': typeof ConsumableHistoriqueRoute
  '/outils/$id': typeof OutilsIdRoute
  '/parametres/emplacements': typeof ParametresEmplacementsRoute
  '/phone/carnet': typeof PhoneCarnetRoute
  '/phone/historique': typeof PhoneHistoriqueRoute
  '/sales/commandes': typeof SalesCommandesRoute
  '/sales/livraisons': typeof SalesLivraisonsRoute
  '/sales/nouveau': typeof SalesNouveauRoute
  '/salles/commandes': typeof SallesCommandesRoute
  '/admin': typeof AdminIndexRoute
  '/atelier': typeof AtelierIndexRoute
  '/boutiques': typeof BoutiquesIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/outils': typeof OutilsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/admin/modules/ajouter': typeof AdminModulesAjouterRoute
  '/admin/modules/nouveau': typeof AdminModulesNouveauRoute
  '/admin/support/faq': typeof AdminSupportFaqRoute
  '/admin/support/messages': typeof AdminSupportMessagesRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/historique': typeof AdminTenantsHistoriqueRoute
  '/computer/atelier/$id': typeof ComputerAtelierIdRoute
  '/computer/atelier/nouveau': typeof ComputerAtelierNouveauRoute
  '/consumable/stock/$id': typeof ConsumableStockIdRoute
  '/consumable/stock/nouveau': typeof ConsumableStockNouveauRoute
  '/phone/atelier/$id': typeof PhoneAtelierIdRoute
  '/phone/atelier/nouveau': typeof PhoneAtelierNouveauRoute
  '/admin/modules': typeof AdminModulesIndexRoute
  '/computer/atelier': typeof ComputerAtelierIndexRoute
  '/consumable/stock': typeof ConsumableStockIndexRoute
  '/phone/atelier': typeof PhoneAtelierIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/admin': typeof AdminRouteWithChildren
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/equipe': typeof EquipeRoute
  '/historique': typeof HistoriqueRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/nouveautes': typeof NouveautesRoute
  '/parametres': typeof ParametresRouteWithChildren
  '/profil': typeof ProfilRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/statistiques': typeof StatistiquesRoute
  '/admin/annonces': typeof AdminAnnoncesRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/modules': typeof AdminModulesRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/prix': typeof AdminPrixRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/tenants': typeof AdminTenantsRouteWithChildren
  '/atelier/$id': typeof AtelierIdRoute
  '/atelier/nouveau': typeof AtelierNouveauRoute
  '/atelier/plan': typeof AtelierPlanRoute
  '/boutiques/$id': typeof BoutiquesIdRoute
  '/boutiques/nouveau': typeof BoutiquesNouveauRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/nouveau': typeof ClientsNouveauRoute
  '/computer/carnet': typeof ComputerCarnetRoute
  '/computer/historique': typeof ComputerHistoriqueRoute
  '/consumable/historique': typeof ConsumableHistoriqueRoute
  '/outils/$id': typeof OutilsIdRoute
  '/parametres/emplacements': typeof ParametresEmplacementsRoute
  '/phone/carnet': typeof PhoneCarnetRoute
  '/phone/historique': typeof PhoneHistoriqueRoute
  '/sales/commandes': typeof SalesCommandesRoute
  '/sales/livraisons': typeof SalesLivraisonsRoute
  '/sales/nouveau': typeof SalesNouveauRoute
  '/salles/commandes': typeof SallesCommandesRoute
  '/admin/': typeof AdminIndexRoute
  '/atelier/': typeof AtelierIndexRoute
  '/boutiques/': typeof BoutiquesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/outils/': typeof OutilsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/admin/modules/ajouter': typeof AdminModulesAjouterRoute
  '/admin/modules/nouveau': typeof AdminModulesNouveauRoute
  '/admin/support/faq': typeof AdminSupportFaqRoute
  '/admin/support/messages': typeof AdminSupportMessagesRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/historique': typeof AdminTenantsHistoriqueRoute
  '/computer/atelier/$id': typeof ComputerAtelierIdRoute
  '/computer/atelier/nouveau': typeof ComputerAtelierNouveauRoute
  '/consumable/stock/$id': typeof ConsumableStockIdRoute
  '/consumable/stock/nouveau': typeof ConsumableStockNouveauRoute
  '/phone/atelier/$id': typeof PhoneAtelierIdRoute
  '/phone/atelier/nouveau': typeof PhoneAtelierNouveauRoute
  '/admin/modules/': typeof AdminModulesIndexRoute
  '/computer/atelier/': typeof ComputerAtelierIndexRoute
  '/consumable/stock/': typeof ConsumableStockIndexRoute
  '/phone/atelier/': typeof PhoneAtelierIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnement'
    | '/admin'
    | '/aide'
    | '/auth'
    | '/categories'
    | '/equipe'
    | '/historique'
    | '/mot-de-passe-oublie'
    | '/nouveautes'
    | '/parametres'
    | '/profil'
    | '/reinitialiser-mot-de-passe'
    | '/statistiques'
    | '/admin/annonces'
    | '/admin/facturation'
    | '/admin/finances'
    | '/admin/messages'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/paiements'
    | '/admin/prix'
    | '/admin/support'
    | '/admin/tenants'
    | '/atelier/$id'
    | '/atelier/nouveau'
    | '/atelier/plan'
    | '/boutiques/$id'
    | '/boutiques/nouveau'
    | '/clients/$id'
    | '/clients/nouveau'
    | '/computer/carnet'
    | '/computer/historique'
    | '/consumable/historique'
    | '/outils/$id'
    | '/parametres/emplacements'
    | '/phone/carnet'
    | '/phone/historique'
    | '/sales/commandes'
    | '/sales/livraisons'
    | '/sales/nouveau'
    | '/salles/commandes'
    | '/admin/'
    | '/atelier/'
    | '/boutiques/'
    | '/clients/'
    | '/outils/'
    | '/sales/'
    | '/admin/modules/ajouter'
    | '/admin/modules/nouveau'
    | '/admin/support/faq'
    | '/admin/support/messages'
    | '/admin/tenants/$id'
    | '/admin/tenants/historique'
    | '/computer/atelier/$id'
    | '/computer/atelier/nouveau'
    | '/consumable/stock/$id'
    | '/consumable/stock/nouveau'
    | '/phone/atelier/$id'
    | '/phone/atelier/nouveau'
    | '/admin/modules/'
    | '/computer/atelier/'
    | '/consumable/stock/'
    | '/phone/atelier/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnement'
    | '/aide'
    | '/auth'
    | '/categories'
    | '/equipe'
    | '/historique'
    | '/mot-de-passe-oublie'
    | '/nouveautes'
    | '/parametres'
    | '/profil'
    | '/reinitialiser-mot-de-passe'
    | '/statistiques'
    | '/admin/annonces'
    | '/admin/facturation'
    | '/admin/finances'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/paiements'
    | '/admin/prix'
    | '/admin/support'
    | '/admin/tenants'
    | '/atelier/$id'
    | '/atelier/nouveau'
    | '/atelier/plan'
    | '/boutiques/$id'
    | '/boutiques/nouveau'
    | '/clients/$id'
    | '/clients/nouveau'
    | '/computer/carnet'
    | '/computer/historique'
    | '/consumable/historique'
    | '/outils/$id'
    | '/parametres/emplacements'
    | '/phone/carnet'
    | '/phone/historique'
    | '/sales/commandes'
    | '/sales/livraisons'
    | '/sales/nouveau'
    | '/salles/commandes'
    | '/admin'
    | '/atelier'
    | '/boutiques'
    | '/clients'
    | '/outils'
    | '/sales'
    | '/admin/modules/ajouter'
    | '/admin/modules/nouveau'
    | '/admin/support/faq'
    | '/admin/support/messages'
    | '/admin/tenants/$id'
    | '/admin/tenants/historique'
    | '/computer/atelier/$id'
    | '/computer/atelier/nouveau'
    | '/consumable/stock/$id'
    | '/consumable/stock/nouveau'
    | '/phone/atelier/$id'
    | '/phone/atelier/nouveau'
    | '/admin/modules'
    | '/computer/atelier'
    | '/consumable/stock'
    | '/phone/atelier'
  id:
    | '__root__'
    | '/'
    | '/abonnement'
    | '/admin'
    | '/aide'
    | '/auth'
    | '/categories'
    | '/equipe'
    | '/historique'
    | '/mot-de-passe-oublie'
    | '/nouveautes'
    | '/parametres'
    | '/profil'
    | '/reinitialiser-mot-de-passe'
    | '/statistiques'
    | '/admin/annonces'
    | '/admin/facturation'
    | '/admin/finances'
    | '/admin/messages'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/paiements'
    | '/admin/prix'
    | '/admin/support'
    | '/admin/tenants'
    | '/atelier/$id'
    | '/atelier/nouveau'
    | '/atelier/plan'
    | '/boutiques/$id'
    | '/boutiques/nouveau'
    | '/clients/$id'
    | '/clients/nouveau'
    | '/computer/carnet'
    | '/computer/historique'
    | '/consumable/historique'
    | '/outils/$id'
    | '/parametres/emplacements'
    | '/phone/carnet'
    | '/phone/historique'
    | '/sales/commandes'
    | '/sales/livraisons'
    | '/sales/nouveau'
    | '/salles/commandes'
    | '/admin/'
    | '/atelier/'
    | '/boutiques/'
    | '/clients/'
    | '/outils/'
    | '/sales/'
    | '/admin/modules/ajouter'
    | '/admin/modules/nouveau'
    | '/admin/support/faq'
    | '/admin/support/messages'
    | '/admin/tenants/$id'
    | '/admin/tenants/historique'
    | '/computer/atelier/$id'
    | '/computer/atelier/nouveau'
    | '/consumable/stock/$id'
    | '/consumable/stock/nouveau'
    | '/phone/atelier/$id'
    | '/phone/atelier/nouveau'
    | '/admin/modules/'
    | '/computer/atelier/'
    | '/consumable/stock/'
    | '/phone/atelier/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementRoute: typeof AbonnementRoute
  AdminRoute: typeof AdminRouteWithChildren
  AideRoute: typeof AideRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  EquipeRoute: typeof EquipeRoute
  HistoriqueRoute: typeof HistoriqueRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  NouveautesRoute: typeof NouveautesRoute
  ParametresRoute: typeof ParametresRouteWithChildren
  ProfilRoute: typeof ProfilRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  StatistiquesRoute: typeof StatistiquesRoute
  AtelierIdRoute: typeof AtelierIdRoute
  AtelierNouveauRoute: typeof AtelierNouveauRoute
  AtelierPlanRoute: typeof AtelierPlanRoute
  BoutiquesIdRoute: typeof BoutiquesIdRoute
  BoutiquesNouveauRoute: typeof BoutiquesNouveauRoute
  ClientsIdRoute: typeof ClientsIdRoute
  ClientsNouveauRoute: typeof ClientsNouveauRoute
  ComputerCarnetRoute: typeof ComputerCarnetRoute
  ComputerHistoriqueRoute: typeof ComputerHistoriqueRoute
  ConsumableHistoriqueRoute: typeof ConsumableHistoriqueRoute
  OutilsIdRoute: typeof OutilsIdRoute
  PhoneCarnetRoute: typeof PhoneCarnetRoute
  PhoneHistoriqueRoute: typeof PhoneHistoriqueRoute
  SalesCommandesRoute: typeof SalesCommandesRoute
  SalesLivraisonsRoute: typeof SalesLivraisonsRoute
  SalesNouveauRoute: typeof SalesNouveauRoute
  SallesCommandesRoute: typeof SallesCommandesRoute
  AtelierIndexRoute: typeof AtelierIndexRoute
  BoutiquesIndexRoute: typeof BoutiquesIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  OutilsIndexRoute: typeof OutilsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  ComputerAtelierIdRoute: typeof ComputerAtelierIdRoute
  ComputerAtelierNouveauRoute: typeof ComputerAtelierNouveauRoute
  ConsumableStockIdRoute: typeof ConsumableStockIdRoute
  ConsumableStockNouveauRoute: typeof ConsumableStockNouveauRoute
  PhoneAtelierIdRoute: typeof PhoneAtelierIdRoute
  PhoneAtelierNouveauRoute: typeof PhoneAtelierNouveauRoute
  ComputerAtelierIndexRoute: typeof ComputerAtelierIndexRoute
  ConsumableStockIndexRoute: typeof ConsumableStockIndexRoute
  PhoneAtelierIndexRoute: typeof PhoneAtelierIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement': {
      id: '/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveautes': {
      id: '/nouveautes'
      path: '/nouveautes'
      fullPath: '/nouveautes'
      preLoaderRoute: typeof NouveautesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/annonces': {
      id: '/admin/annonces'
      path: '/annonces'
      fullPath: '/admin/annonces'
      preLoaderRoute: typeof AdminAnnoncesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturation': {
      id: '/admin/facturation'
      path: '/facturation'
      fullPath: '/admin/facturation'
      preLoaderRoute: typeof AdminFacturationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finances': {
      id: '/admin/finances'
      path: '/finances'
      fullPath: '/admin/finances'
      preLoaderRoute: typeof AdminFinancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prix': {
      id: '/admin/prix'
      path: '/prix'
      fullPath: '/admin/prix'
      preLoaderRoute: typeof AdminPrixRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/atelier/': {
      id: '/atelier/'
      path: '/atelier'
      fullPath: '/atelier/'
      preLoaderRoute: typeof AtelierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier/$id': {
      id: '/atelier/$id'
      path: '/atelier/$id'
      fullPath: '/atelier/$id'
      preLoaderRoute: typeof AtelierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier/nouveau': {
      id: '/atelier/nouveau'
      path: '/atelier/nouveau'
      fullPath: '/atelier/nouveau'
      preLoaderRoute: typeof AtelierNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier/plan': {
      id: '/atelier/plan'
      path: '/atelier/plan'
      fullPath: '/atelier/plan'
      preLoaderRoute: typeof AtelierPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques/': {
      id: '/boutiques/'
      path: '/boutiques'
      fullPath: '/boutiques/'
      preLoaderRoute: typeof BoutiquesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques/$id': {
      id: '/boutiques/$id'
      path: '/boutiques/$id'
      fullPath: '/boutiques/$id'
      preLoaderRoute: typeof BoutiquesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques/nouveau': {
      id: '/boutiques/nouveau'
      path: '/boutiques/nouveau'
      fullPath: '/boutiques/nouveau'
      preLoaderRoute: typeof BoutiquesNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/nouveau': {
      id: '/clients/nouveau'
      path: '/clients/nouveau'
      fullPath: '/clients/nouveau'
      preLoaderRoute: typeof ClientsNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer/carnet': {
      id: '/computer/carnet'
      path: '/computer/carnet'
      fullPath: '/computer/carnet'
      preLoaderRoute: typeof ComputerCarnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer/historique': {
      id: '/computer/historique'
      path: '/computer/historique'
      fullPath: '/computer/historique'
      preLoaderRoute: typeof ComputerHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumable/historique': {
      id: '/consumable/historique'
      path: '/consumable/historique'
      fullPath: '/consumable/historique'
      preLoaderRoute: typeof ConsumableHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/': {
      id: '/outils/'
      path: '/outils'
      fullPath: '/outils/'
      preLoaderRoute: typeof OutilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/$id': {
      id: '/outils/$id'
      path: '/outils/$id'
      fullPath: '/outils/$id'
      preLoaderRoute: typeof OutilsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres/emplacements': {
      id: '/parametres/emplacements'
      path: '/emplacements'
      fullPath: '/parametres/emplacements'
      preLoaderRoute: typeof ParametresEmplacementsRouteImport
      parentRoute: typeof ParametresRoute
    }
    '/phone/carnet': {
      id: '/phone/carnet'
      path: '/phone/carnet'
      fullPath: '/phone/carnet'
      preLoaderRoute: typeof PhoneCarnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/historique': {
      id: '/phone/historique'
      path: '/phone/historique'
      fullPath: '/phone/historique'
      preLoaderRoute: typeof PhoneHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/commandes': {
      id: '/sales/commandes'
      path: '/sales/commandes'
      fullPath: '/sales/commandes'
      preLoaderRoute: typeof SalesCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/livraisons': {
      id: '/sales/livraisons'
      path: '/sales/livraisons'
      fullPath: '/sales/livraisons'
      preLoaderRoute: typeof SalesLivraisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/nouveau': {
      id: '/sales/nouveau'
      path: '/sales/nouveau'
      fullPath: '/sales/nouveau'
      preLoaderRoute: typeof SalesNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salles/commandes': {
      id: '/salles/commandes'
      path: '/salles/commandes'
      fullPath: '/salles/commandes'
      preLoaderRoute: typeof SallesCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/modules/': {
      id: '/admin/modules/'
      path: '/'
      fullPath: '/admin/modules/'
      preLoaderRoute: typeof AdminModulesIndexRouteImport
      parentRoute: typeof AdminModulesRoute
    }
    '/admin/modules/ajouter': {
      id: '/admin/modules/ajouter'
      path: '/ajouter'
      fullPath: '/admin/modules/ajouter'
      preLoaderRoute: typeof AdminModulesAjouterRouteImport
      parentRoute: typeof AdminModulesRoute
    }
    '/admin/modules/nouveau': {
      id: '/admin/modules/nouveau'
      path: '/nouveau'
      fullPath: '/admin/modules/nouveau'
      preLoaderRoute: typeof AdminModulesNouveauRouteImport
      parentRoute: typeof AdminModulesRoute
    }
    '/admin/support/faq': {
      id: '/admin/support/faq'
      path: '/faq'
      fullPath: '/admin/support/faq'
      preLoaderRoute: typeof AdminSupportFaqRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/support/messages': {
      id: '/admin/support/messages'
      path: '/messages'
      fullPath: '/admin/support/messages'
      preLoaderRoute: typeof AdminSupportMessagesRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/tenants/$id': {
      id: '/admin/tenants/$id'
      path: '/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
    '/admin/tenants/historique': {
      id: '/admin/tenants/historique'
      path: '/historique'
      fullPath: '/admin/tenants/historique'
      preLoaderRoute: typeof AdminTenantsHistoriqueRouteImport
      parentRoute: typeof AdminTenantsRoute
    }
    '/computer/atelier/': {
      id: '/computer/atelier/'
      path: '/computer/atelier'
      fullPath: '/computer/atelier/'
      preLoaderRoute: typeof ComputerAtelierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer/atelier/$id': {
      id: '/computer/atelier/$id'
      path: '/computer/atelier/$id'
      fullPath: '/computer/atelier/$id'
      preLoaderRoute: typeof ComputerAtelierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer/atelier/nouveau': {
      id: '/computer/atelier/nouveau'
      path: '/computer/atelier/nouveau'
      fullPath: '/computer/atelier/nouveau'
      preLoaderRoute: typeof ComputerAtelierNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumable/stock/': {
      id: '/consumable/stock/'
      path: '/consumable/stock'
      fullPath: '/consumable/stock/'
      preLoaderRoute: typeof ConsumableStockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumable/stock/$id': {
      id: '/consumable/stock/$id'
      path: '/consumable/stock/$id'
      fullPath: '/consumable/stock/$id'
      preLoaderRoute: typeof ConsumableStockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumable/stock/nouveau': {
      id: '/consumable/stock/nouveau'
      path: '/consumable/stock/nouveau'
      fullPath: '/consumable/stock/nouveau'
      preLoaderRoute: typeof ConsumableStockNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/atelier/': {
      id: '/phone/atelier/'
      path: '/phone/atelier'
      fullPath: '/phone/atelier/'
      preLoaderRoute: typeof PhoneAtelierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/atelier/$id': {
      id: '/phone/atelier/$id'
      path: '/phone/atelier/$id'
      fullPath: '/phone/atelier/$id'
      preLoaderRoute: typeof PhoneAtelierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/atelier/nouveau': {
      id: '/phone/atelier/nouveau'
      path: '/phone/atelier/nouveau'
      fullPath: '/phone/atelier/nouveau'
      preLoaderRoute: typeof PhoneAtelierNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminModulesRouteChildren {
  AdminModulesAjouterRoute: typeof AdminModulesAjouterRoute
  AdminModulesNouveauRoute: typeof AdminModulesNouveauRoute
  AdminModulesIndexRoute: typeof AdminModulesIndexRoute
}

const AdminModulesRouteChildren: AdminModulesRouteChildren = {
  AdminModulesAjouterRoute: AdminModulesAjouterRoute,
  AdminModulesNouveauRoute: AdminModulesNouveauRoute,
  AdminModulesIndexRoute: AdminModulesIndexRoute,
}

const AdminModulesRouteWithChildren = AdminModulesRoute._addFileChildren(
  AdminModulesRouteChildren,
)

interface AdminSupportRouteChildren {
  AdminSupportFaqRoute: typeof AdminSupportFaqRoute
  AdminSupportMessagesRoute: typeof AdminSupportMessagesRoute
}

const AdminSupportRouteChildren: AdminSupportRouteChildren = {
  AdminSupportFaqRoute: AdminSupportFaqRoute,
  AdminSupportMessagesRoute: AdminSupportMessagesRoute,
}

const AdminSupportRouteWithChildren = AdminSupportRoute._addFileChildren(
  AdminSupportRouteChildren,
)

interface AdminTenantsRouteChildren {
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
  AdminTenantsHistoriqueRoute: typeof AdminTenantsHistoriqueRoute
}

const AdminTenantsRouteChildren: AdminTenantsRouteChildren = {
  AdminTenantsIdRoute: AdminTenantsIdRoute,
  AdminTenantsHistoriqueRoute: AdminTenantsHistoriqueRoute,
}

const AdminTenantsRouteWithChildren = AdminTenantsRoute._addFileChildren(
  AdminTenantsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnnoncesRoute: typeof AdminAnnoncesRoute
  AdminFacturationRoute: typeof AdminFacturationRoute
  AdminFinancesRoute: typeof AdminFinancesRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminModulesRoute: typeof AdminModulesRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminPrixRoute: typeof AdminPrixRoute
  AdminSupportRoute: typeof AdminSupportRouteWithChildren
  AdminTenantsRoute: typeof AdminTenantsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnoncesRoute: AdminAnnoncesRoute,
  AdminFacturationRoute: AdminFacturationRoute,
  AdminFinancesRoute: AdminFinancesRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminModulesRoute: AdminModulesRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminPrixRoute: AdminPrixRoute,
  AdminSupportRoute: AdminSupportRouteWithChildren,
  AdminTenantsRoute: AdminTenantsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParametresRouteChildren {
  ParametresEmplacementsRoute: typeof ParametresEmplacementsRoute
}

const ParametresRouteChildren: ParametresRouteChildren = {
  ParametresEmplacementsRoute: ParametresEmplacementsRoute,
}

const ParametresRouteWithChildren = ParametresRoute._addFileChildren(
  ParametresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementRoute: AbonnementRoute,
  AdminRoute: AdminRouteWithChildren,
  AideRoute: AideRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  EquipeRoute: EquipeRoute,
  HistoriqueRoute: HistoriqueRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  NouveautesRoute: NouveautesRoute,
  ParametresRoute: ParametresRouteWithChildren,
  ProfilRoute: ProfilRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  StatistiquesRoute: StatistiquesRoute,
  AtelierIdRoute: AtelierIdRoute,
  AtelierNouveauRoute: AtelierNouveauRoute,
  AtelierPlanRoute: AtelierPlanRoute,
  BoutiquesIdRoute: BoutiquesIdRoute,
  BoutiquesNouveauRoute: BoutiquesNouveauRoute,
  ClientsIdRoute: ClientsIdRoute,
  ClientsNouveauRoute: ClientsNouveauRoute,
  ComputerCarnetRoute: ComputerCarnetRoute,
  ComputerHistoriqueRoute: ComputerHistoriqueRoute,
  ConsumableHistoriqueRoute: ConsumableHistoriqueRoute,
  OutilsIdRoute: OutilsIdRoute,
  PhoneCarnetRoute: PhoneCarnetRoute,
  PhoneHistoriqueRoute: PhoneHistoriqueRoute,
  SalesCommandesRoute: SalesCommandesRoute,
  SalesLivraisonsRoute: SalesLivraisonsRoute,
  SalesNouveauRoute: SalesNouveauRoute,
  SallesCommandesRoute: SallesCommandesRoute,
  AtelierIndexRoute: AtelierIndexRoute,
  BoutiquesIndexRoute: BoutiquesIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  OutilsIndexRoute: OutilsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  ComputerAtelierIdRoute: ComputerAtelierIdRoute,
  ComputerAtelierNouveauRoute: ComputerAtelierNouveauRoute,
  ConsumableStockIdRoute: ConsumableStockIdRoute,
  ConsumableStockNouveauRoute: ConsumableStockNouveauRoute,
  PhoneAtelierIdRoute: PhoneAtelierIdRoute,
  PhoneAtelierNouveauRoute: PhoneAtelierNouveauRoute,
  ComputerAtelierIndexRoute: ComputerAtelierIndexRoute,
  ConsumableStockIndexRoute: ConsumableStockIndexRoute,
  PhoneAtelierIndexRoute: PhoneAtelierIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
