/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbonnementRouteImport } from './routes/abonnement'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as StatistiquesRouteImport } from './routes/statistiques'
import { Route as AtelierIndexRouteImport } from './routes/atelier.index'
import { Route as AtelierIdRouteImport } from './routes/atelier.$id'
import { Route as AtelierNouveauRouteImport } from './routes/atelier.nouveau'
import { Route as BoutiquesIndexRouteImport } from './routes/boutiques.index'
import { Route as BoutiquesIdRouteImport } from './routes/boutiques.$id'
import { Route as BoutiquesNouveauRouteImport } from './routes/boutiques.nouveau'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as ClientsNouveauRouteImport } from './routes/clients.nouveau'
import { Route as ComputerCarnetRouteImport } from './routes/computer/carnet'
import { Route as ComputerHistoriqueRouteImport } from './routes/computer/historique'
import { Route as ConsumableHistoriqueRouteImport } from './routes/consumable/historique'
import { Route as OutilsIndexRouteImport } from './routes/outils.index'
import { Route as OutilsIdRouteImport } from './routes/outils.$id'
import { Route as PhoneCarnetRouteImport } from './routes/phone/carnet'
import { Route as PhoneHistoriqueRouteImport } from './routes/phone/historique'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as SalesCommandesRouteImport } from './routes/sales/commandes'
import { Route as SalesLivraisonsRouteImport } from './routes/sales/livraisons'
import { Route as SalesNouveauRouteImport } from './routes/sales/nouveau'
import { Route as ComputerAtelierIndexRouteImport } from './routes/computer/atelier/index'
import { Route as ComputerAtelierIdRouteImport } from './routes/computer/atelier/$id'
import { Route as ComputerAtelierNouveauRouteImport } from './routes/computer/atelier/nouveau'
import { Route as ConsumableStockIndexRouteImport } from './routes/consumable/stock/index'
import { Route as ConsumableStockIdRouteImport } from './routes/consumable/stock/$id'
import { Route as ConsumableStockNouveauRouteImport } from './routes/consumable/stock/nouveau'
import { Route as PhoneAtelierIndexRouteImport } from './routes/phone/atelier/index'
import { Route as PhoneAtelierIdRouteImport } from './routes/phone/atelier/$id'
import { Route as PhoneAtelierNouveauRouteImport } from './routes/phone/atelier/nouveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbonnementRoute = AbonnementRouteImport.update({
  id: '/abonnement',
  path: '/abonnement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const StatistiquesRoute = StatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierIndexRoute = AtelierIndexRouteImport.update({
  id: '/atelier/',
  path: '/atelier/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierIdRoute = AtelierIdRouteImport.update({
  id: '/atelier/$id',
  path: '/atelier/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierNouveauRoute = AtelierNouveauRouteImport.update({
  id: '/atelier/nouveau',
  path: '/atelier/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesIndexRoute = BoutiquesIndexRouteImport.update({
  id: '/boutiques/',
  path: '/boutiques/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesIdRoute = BoutiquesIdRouteImport.update({
  id: '/boutiques/$id',
  path: '/boutiques/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiquesNouveauRoute = BoutiquesNouveauRouteImport.update({
  id: '/boutiques/nouveau',
  path: '/boutiques/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNouveauRoute = ClientsNouveauRouteImport.update({
  id: '/clients/nouveau',
  path: '/clients/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerCarnetRoute = ComputerCarnetRouteImport.update({
  id: '/computer/carnet',
  path: '/computer/carnet',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerHistoriqueRoute = ComputerHistoriqueRouteImport.update({
  id: '/computer/historique',
  path: '/computer/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumableHistoriqueRoute = ConsumableHistoriqueRouteImport.update({
  id: '/consumable/historique',
  path: '/consumable/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsIndexRoute = OutilsIndexRouteImport.update({
  id: '/outils/',
  path: '/outils/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutilsIdRoute = OutilsIdRouteImport.update({
  id: '/outils/$id',
  path: '/outils/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneCarnetRoute = PhoneCarnetRouteImport.update({
  id: '/phone/carnet',
  path: '/phone/carnet',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneHistoriqueRoute = PhoneHistoriqueRouteImport.update({
  id: '/phone/historique',
  path: '/phone/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCommandesRoute = SalesCommandesRouteImport.update({
  id: '/sales/commandes',
  path: '/sales/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesLivraisonsRoute = SalesLivraisonsRouteImport.update({
  id: '/sales/livraisons',
  path: '/sales/livraisons',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNouveauRoute = SalesNouveauRouteImport.update({
  id: '/sales/nouveau',
  path: '/sales/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerAtelierIndexRoute = ComputerAtelierIndexRouteImport.update({
  id: '/computer/atelier/',
  path: '/computer/atelier/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerAtelierIdRoute = ComputerAtelierIdRouteImport.update({
  id: '/computer/atelier/$id',
  path: '/computer/atelier/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerAtelierNouveauRoute = ComputerAtelierNouveauRouteImport.update({
  id: '/computer/atelier/nouveau',
  path: '/computer/atelier/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumableStockIndexRoute = ConsumableStockIndexRouteImport.update({
  id: '/consumable/stock/',
  path: '/consumable/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumableStockIdRoute = ConsumableStockIdRouteImport.update({
  id: '/consumable/stock/$id',
  path: '/consumable/stock/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumableStockNouveauRoute = ConsumableStockNouveauRouteImport.update({
  id: '/consumable/stock/nouveau',
  path: '/consumable/stock/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneAtelierIndexRoute = PhoneAtelierIndexRouteImport.update({
  id: '/phone/atelier/',
  path: '/phone/atelier/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneAtelierIdRoute = PhoneAtelierIdRouteImport.update({
  id: '/phone/atelier/$id',
  path: '/phone/atelier/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneAtelierNouveauRoute = PhoneAtelierNouveauRouteImport.update({
  id: '/phone/atelier/nouveau',
  path: '/phone/atelier/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/equipe': typeof EquipeRoute
  '/historique': typeof HistoriqueRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/parametres': typeof ParametresRoute
  '/profil': typeof ProfilRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/statistiques': typeof StatistiquesRoute
  '/atelier/$id': typeof AtelierIdRoute
  '/atelier/nouveau': typeof AtelierNouveauRoute
  '/boutiques/$id': typeof BoutiquesIdRoute
  '/boutiques/nouveau': typeof BoutiquesNouveauRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/nouveau': typeof ClientsNouveauRoute
  '/computer/carnet': typeof ComputerCarnetRoute
  '/computer/historique': typeof ComputerHistoriqueRoute
  '/consumable/historique': typeof ConsumableHistoriqueRoute
  '/outils/$id': typeof OutilsIdRoute
  '/phone/carnet': typeof PhoneCarnetRoute
  '/phone/historique': typeof PhoneHistoriqueRoute
  '/sales/commandes': typeof SalesCommandesRoute
  '/sales/livraisons': typeof SalesLivraisonsRoute
  '/sales/nouveau': typeof SalesNouveauRoute
  '/atelier/': typeof AtelierIndexRoute
  '/boutiques/': typeof BoutiquesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/outils/': typeof OutilsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/computer/atelier/$id': typeof ComputerAtelierIdRoute
  '/computer/atelier/nouveau': typeof ComputerAtelierNouveauRoute
  '/consumable/stock/$id': typeof ConsumableStockIdRoute
  '/consumable/stock/nouveau': typeof ConsumableStockNouveauRoute
  '/phone/atelier/$id': typeof PhoneAtelierIdRoute
  '/phone/atelier/nouveau': typeof PhoneAtelierNouveauRoute
  '/computer/atelier/': typeof ComputerAtelierIndexRoute
  '/consumable/stock/': typeof ConsumableStockIndexRoute
  '/phone/atelier/': typeof PhoneAtelierIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/equipe': typeof EquipeRoute
  '/historique': typeof HistoriqueRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/parametres': typeof ParametresRoute
  '/profil': typeof ProfilRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/statistiques': typeof StatistiquesRoute
  '/atelier/$id': typeof AtelierIdRoute
  '/atelier/nouveau': typeof AtelierNouveauRoute
  '/boutiques/$id': typeof BoutiquesIdRoute
  '/boutiques/nouveau': typeof BoutiquesNouveauRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/nouveau': typeof ClientsNouveauRoute
  '/computer/carnet': typeof ComputerCarnetRoute
  '/computer/historique': typeof ComputerHistoriqueRoute
  '/consumable/historique': typeof ConsumableHistoriqueRoute
  '/outils/$id': typeof OutilsIdRoute
  '/phone/carnet': typeof PhoneCarnetRoute
  '/phone/historique': typeof PhoneHistoriqueRoute
  '/sales/commandes': typeof SalesCommandesRoute
  '/sales/livraisons': typeof SalesLivraisonsRoute
  '/sales/nouveau': typeof SalesNouveauRoute
  '/atelier': typeof AtelierIndexRoute
  '/boutiques': typeof BoutiquesIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/outils': typeof OutilsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/computer/atelier/$id': typeof ComputerAtelierIdRoute
  '/computer/atelier/nouveau': typeof ComputerAtelierNouveauRoute
  '/consumable/stock/$id': typeof ConsumableStockIdRoute
  '/consumable/stock/nouveau': typeof ConsumableStockNouveauRoute
  '/phone/atelier/$id': typeof PhoneAtelierIdRoute
  '/phone/atelier/nouveau': typeof PhoneAtelierNouveauRoute
  '/computer/atelier': typeof ComputerAtelierIndexRoute
  '/consumable/stock': typeof ConsumableStockIndexRoute
  '/phone/atelier': typeof PhoneAtelierIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abonnement': typeof AbonnementRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/categories': typeof CategoriesRoute
  '/equipe': typeof EquipeRoute
  '/historique': typeof HistoriqueRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/parametres': typeof ParametresRoute
  '/profil': typeof ProfilRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/statistiques': typeof StatistiquesRoute
  '/atelier/$id': typeof AtelierIdRoute
  '/atelier/nouveau': typeof AtelierNouveauRoute
  '/boutiques/$id': typeof BoutiquesIdRoute
  '/boutiques/nouveau': typeof BoutiquesNouveauRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/nouveau': typeof ClientsNouveauRoute
  '/computer/carnet': typeof ComputerCarnetRoute
  '/computer/historique': typeof ComputerHistoriqueRoute
  '/consumable/historique': typeof ConsumableHistoriqueRoute
  '/outils/$id': typeof OutilsIdRoute
  '/phone/carnet': typeof PhoneCarnetRoute
  '/phone/historique': typeof PhoneHistoriqueRoute
  '/sales/commandes': typeof SalesCommandesRoute
  '/sales/livraisons': typeof SalesLivraisonsRoute
  '/sales/nouveau': typeof SalesNouveauRoute
  '/atelier/': typeof AtelierIndexRoute
  '/boutiques/': typeof BoutiquesIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/outils/': typeof OutilsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/computer/atelier/$id': typeof ComputerAtelierIdRoute
  '/computer/atelier/nouveau': typeof ComputerAtelierNouveauRoute
  '/consumable/stock/$id': typeof ConsumableStockIdRoute
  '/consumable/stock/nouveau': typeof ConsumableStockNouveauRoute
  '/phone/atelier/$id': typeof PhoneAtelierIdRoute
  '/phone/atelier/nouveau': typeof PhoneAtelierNouveauRoute
  '/computer/atelier/': typeof ComputerAtelierIndexRoute
  '/consumable/stock/': typeof ConsumableStockIndexRoute
  '/phone/atelier/': typeof PhoneAtelierIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abonnement'
    | '/admin'
    | '/auth'
    | '/categories'
    | '/equipe'
    | '/historique'
    | '/mot-de-passe-oublie'
    | '/parametres'
    | '/profil'
    | '/reinitialiser-mot-de-passe'
    | '/statistiques'
    | '/atelier/$id'
    | '/atelier/nouveau'
    | '/boutiques/$id'
    | '/boutiques/nouveau'
    | '/clients/$id'
    | '/clients/nouveau'
    | '/computer/carnet'
    | '/computer/historique'
    | '/consumable/historique'
    | '/outils/$id'
    | '/phone/carnet'
    | '/phone/historique'
    | '/sales/commandes'
    | '/sales/livraisons'
    | '/sales/nouveau'
    | '/atelier/'
    | '/boutiques/'
    | '/clients/'
    | '/outils/'
    | '/sales/'
    | '/computer/atelier/$id'
    | '/computer/atelier/nouveau'
    | '/consumable/stock/$id'
    | '/consumable/stock/nouveau'
    | '/phone/atelier/$id'
    | '/phone/atelier/nouveau'
    | '/computer/atelier/'
    | '/consumable/stock/'
    | '/phone/atelier/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abonnement'
    | '/admin'
    | '/auth'
    | '/categories'
    | '/equipe'
    | '/historique'
    | '/mot-de-passe-oublie'
    | '/parametres'
    | '/profil'
    | '/reinitialiser-mot-de-passe'
    | '/statistiques'
    | '/atelier/$id'
    | '/atelier/nouveau'
    | '/boutiques/$id'
    | '/boutiques/nouveau'
    | '/clients/$id'
    | '/clients/nouveau'
    | '/computer/carnet'
    | '/computer/historique'
    | '/consumable/historique'
    | '/outils/$id'
    | '/phone/carnet'
    | '/phone/historique'
    | '/sales/commandes'
    | '/sales/livraisons'
    | '/sales/nouveau'
    | '/atelier'
    | '/boutiques'
    | '/clients'
    | '/outils'
    | '/sales'
    | '/computer/atelier/$id'
    | '/computer/atelier/nouveau'
    | '/consumable/stock/$id'
    | '/consumable/stock/nouveau'
    | '/phone/atelier/$id'
    | '/phone/atelier/nouveau'
    | '/computer/atelier'
    | '/consumable/stock'
    | '/phone/atelier'
  id:
    | '__root__'
    | '/'
    | '/abonnement'
    | '/admin'
    | '/auth'
    | '/categories'
    | '/equipe'
    | '/historique'
    | '/mot-de-passe-oublie'
    | '/parametres'
    | '/profil'
    | '/reinitialiser-mot-de-passe'
    | '/statistiques'
    | '/atelier/$id'
    | '/atelier/nouveau'
    | '/boutiques/$id'
    | '/boutiques/nouveau'
    | '/clients/$id'
    | '/clients/nouveau'
    | '/computer/carnet'
    | '/computer/historique'
    | '/consumable/historique'
    | '/outils/$id'
    | '/phone/carnet'
    | '/phone/historique'
    | '/sales/commandes'
    | '/sales/livraisons'
    | '/sales/nouveau'
    | '/atelier/'
    | '/boutiques/'
    | '/clients/'
    | '/outils/'
    | '/sales/'
    | '/computer/atelier/$id'
    | '/computer/atelier/nouveau'
    | '/consumable/stock/$id'
    | '/consumable/stock/nouveau'
    | '/phone/atelier/$id'
    | '/phone/atelier/nouveau'
    | '/computer/atelier/'
    | '/consumable/stock/'
    | '/phone/atelier/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbonnementRoute: typeof AbonnementRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CategoriesRoute: typeof CategoriesRoute
  EquipeRoute: typeof EquipeRoute
  HistoriqueRoute: typeof HistoriqueRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  ParametresRoute: typeof ParametresRoute
  ProfilRoute: typeof ProfilRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
  StatistiquesRoute: typeof StatistiquesRoute
  AtelierIdRoute: typeof AtelierIdRoute
  AtelierNouveauRoute: typeof AtelierNouveauRoute
  BoutiquesIdRoute: typeof BoutiquesIdRoute
  BoutiquesNouveauRoute: typeof BoutiquesNouveauRoute
  ClientsIdRoute: typeof ClientsIdRoute
  ClientsNouveauRoute: typeof ClientsNouveauRoute
  ComputerCarnetRoute: typeof ComputerCarnetRoute
  ComputerHistoriqueRoute: typeof ComputerHistoriqueRoute
  ConsumableHistoriqueRoute: typeof ConsumableHistoriqueRoute
  OutilsIdRoute: typeof OutilsIdRoute
  PhoneCarnetRoute: typeof PhoneCarnetRoute
  PhoneHistoriqueRoute: typeof PhoneHistoriqueRoute
  SalesCommandesRoute: typeof SalesCommandesRoute
  SalesLivraisonsRoute: typeof SalesLivraisonsRoute
  SalesNouveauRoute: typeof SalesNouveauRoute
  AtelierIndexRoute: typeof AtelierIndexRoute
  BoutiquesIndexRoute: typeof BoutiquesIndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  OutilsIndexRoute: typeof OutilsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  ComputerAtelierIdRoute: typeof ComputerAtelierIdRoute
  ComputerAtelierNouveauRoute: typeof ComputerAtelierNouveauRoute
  ConsumableStockIdRoute: typeof ConsumableStockIdRoute
  ConsumableStockNouveauRoute: typeof ConsumableStockNouveauRoute
  PhoneAtelierIdRoute: typeof PhoneAtelierIdRoute
  PhoneAtelierNouveauRoute: typeof PhoneAtelierNouveauRoute
  ComputerAtelierIndexRoute: typeof ComputerAtelierIndexRoute
  ConsumableStockIndexRoute: typeof ConsumableStockIndexRoute
  PhoneAtelierIndexRoute: typeof PhoneAtelierIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abonnement': {
      id: '/abonnement'
      path: '/abonnement'
      fullPath: '/abonnement'
      preLoaderRoute: typeof AbonnementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistiques': {
      id: '/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof StatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier/': {
      id: '/atelier/'
      path: '/atelier'
      fullPath: '/atelier/'
      preLoaderRoute: typeof AtelierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier/$id': {
      id: '/atelier/$id'
      path: '/atelier/$id'
      fullPath: '/atelier/$id'
      preLoaderRoute: typeof AtelierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier/nouveau': {
      id: '/atelier/nouveau'
      path: '/atelier/nouveau'
      fullPath: '/atelier/nouveau'
      preLoaderRoute: typeof AtelierNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques/': {
      id: '/boutiques/'
      path: '/boutiques'
      fullPath: '/boutiques/'
      preLoaderRoute: typeof BoutiquesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques/$id': {
      id: '/boutiques/$id'
      path: '/boutiques/$id'
      fullPath: '/boutiques/$id'
      preLoaderRoute: typeof BoutiquesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutiques/nouveau': {
      id: '/boutiques/nouveau'
      path: '/boutiques/nouveau'
      fullPath: '/boutiques/nouveau'
      preLoaderRoute: typeof BoutiquesNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/nouveau': {
      id: '/clients/nouveau'
      path: '/clients/nouveau'
      fullPath: '/clients/nouveau'
      preLoaderRoute: typeof ClientsNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer/carnet': {
      id: '/computer/carnet'
      path: '/computer/carnet'
      fullPath: '/computer/carnet'
      preLoaderRoute: typeof ComputerCarnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer/historique': {
      id: '/computer/historique'
      path: '/computer/historique'
      fullPath: '/computer/historique'
      preLoaderRoute: typeof ComputerHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumable/historique': {
      id: '/consumable/historique'
      path: '/consumable/historique'
      fullPath: '/consumable/historique'
      preLoaderRoute: typeof ConsumableHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/': {
      id: '/outils/'
      path: '/outils'
      fullPath: '/outils/'
      preLoaderRoute: typeof OutilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outils/$id': {
      id: '/outils/$id'
      path: '/outils/$id'
      fullPath: '/outils/$id'
      preLoaderRoute: typeof OutilsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/carnet': {
      id: '/phone/carnet'
      path: '/phone/carnet'
      fullPath: '/phone/carnet'
      preLoaderRoute: typeof PhoneCarnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/historique': {
      id: '/phone/historique'
      path: '/phone/historique'
      fullPath: '/phone/historique'
      preLoaderRoute: typeof PhoneHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/commandes': {
      id: '/sales/commandes'
      path: '/sales/commandes'
      fullPath: '/sales/commandes'
      preLoaderRoute: typeof SalesCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/livraisons': {
      id: '/sales/livraisons'
      path: '/sales/livraisons'
      fullPath: '/sales/livraisons'
      preLoaderRoute: typeof SalesLivraisonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/nouveau': {
      id: '/sales/nouveau'
      path: '/sales/nouveau'
      fullPath: '/sales/nouveau'
      preLoaderRoute: typeof SalesNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer/atelier/': {
      id: '/computer/atelier/'
      path: '/computer/atelier'
      fullPath: '/computer/atelier/'
      preLoaderRoute: typeof ComputerAtelierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer/atelier/$id': {
      id: '/computer/atelier/$id'
      path: '/computer/atelier/$id'
      fullPath: '/computer/atelier/$id'
      preLoaderRoute: typeof ComputerAtelierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer/atelier/nouveau': {
      id: '/computer/atelier/nouveau'
      path: '/computer/atelier/nouveau'
      fullPath: '/computer/atelier/nouveau'
      preLoaderRoute: typeof ComputerAtelierNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumable/stock/': {
      id: '/consumable/stock/'
      path: '/consumable/stock'
      fullPath: '/consumable/stock/'
      preLoaderRoute: typeof ConsumableStockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumable/stock/$id': {
      id: '/consumable/stock/$id'
      path: '/consumable/stock/$id'
      fullPath: '/consumable/stock/$id'
      preLoaderRoute: typeof ConsumableStockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumable/stock/nouveau': {
      id: '/consumable/stock/nouveau'
      path: '/consumable/stock/nouveau'
      fullPath: '/consumable/stock/nouveau'
      preLoaderRoute: typeof ConsumableStockNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/atelier/': {
      id: '/phone/atelier/'
      path: '/phone/atelier'
      fullPath: '/phone/atelier/'
      preLoaderRoute: typeof PhoneAtelierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/atelier/$id': {
      id: '/phone/atelier/$id'
      path: '/phone/atelier/$id'
      fullPath: '/phone/atelier/$id'
      preLoaderRoute: typeof PhoneAtelierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone/atelier/nouveau': {
      id: '/phone/atelier/nouveau'
      path: '/phone/atelier/nouveau'
      fullPath: '/phone/atelier/nouveau'
      preLoaderRoute: typeof PhoneAtelierNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbonnementRoute: AbonnementRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CategoriesRoute: CategoriesRoute,
  EquipeRoute: EquipeRoute,
  HistoriqueRoute: HistoriqueRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  ParametresRoute: ParametresRoute,
  ProfilRoute: ProfilRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
  StatistiquesRoute: StatistiquesRoute,
  AtelierIdRoute: AtelierIdRoute,
  AtelierNouveauRoute: AtelierNouveauRoute,
  BoutiquesIdRoute: BoutiquesIdRoute,
  BoutiquesNouveauRoute: BoutiquesNouveauRoute,
  ClientsIdRoute: ClientsIdRoute,
  ClientsNouveauRoute: ClientsNouveauRoute,
  ComputerCarnetRoute: ComputerCarnetRoute,
  ComputerHistoriqueRoute: ComputerHistoriqueRoute,
  ConsumableHistoriqueRoute: ConsumableHistoriqueRoute,
  OutilsIdRoute: OutilsIdRoute,
  PhoneCarnetRoute: PhoneCarnetRoute,
  PhoneHistoriqueRoute: PhoneHistoriqueRoute,
  SalesCommandesRoute: SalesCommandesRoute,
  SalesLivraisonsRoute: SalesLivraisonsRoute,
  SalesNouveauRoute: SalesNouveauRoute,
  AtelierIndexRoute: AtelierIndexRoute,
  BoutiquesIndexRoute: BoutiquesIndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  OutilsIndexRoute: OutilsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  ComputerAtelierIdRoute: ComputerAtelierIdRoute,
  ComputerAtelierNouveauRoute: ComputerAtelierNouveauRoute,
  ConsumableStockIdRoute: ConsumableStockIdRoute,
  ConsumableStockNouveauRoute: ConsumableStockNouveauRoute,
  PhoneAtelierIdRoute: PhoneAtelierIdRoute,
  PhoneAtelierNouveauRoute: PhoneAtelierNouveauRoute,
  ComputerAtelierIndexRoute: ComputerAtelierIndexRoute,
  ConsumableStockIndexRoute: ConsumableStockIndexRoute,
  PhoneAtelierIndexRoute: PhoneAtelierIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
